export const db = {
  vehicles: [
    {
      id: 1,
      licensePlate: 'ABC-1234',
      make: 'Isuzu',
      model: 'F-Series',
      year: 2020,
      type: 'Truck',
      status: 'active',
      location: 'Riyadh, Saudi Arabia',
      driver: 'Fahad Al Saud',
      lastServiceDate: '2024-05-10',
      warnings: 'No Warnings',
      progress: 80
    },
    {
      id: 2,
      licensePlate: 'XYZ-5678',
      make: 'Mercedes',
      model: 'Actros',
      year: 2019,
      type: 'Trailer',
      status: 'maintenance',
      location: 'Jeddah, Saudi Arabia',
      driver: 'Aisha Al Harbi',
      lastServiceDate: '2024-04-22',
      warnings: 'Oil Change Needed',
      progress: 40
    },
    {
      id: 3,
      licensePlate: 'JKL-9101',
      make: 'Volvo',
      model: 'FH',
      year: 2021,
      type: 'Tanker',
      status: 'inactive',
      location: 'Dammam, Saudi Arabia',
      driver: 'Salman Al Qahtani',
      lastServiceDate: '2024-03-15',
      warnings: 'No Warnings',
      progress: 0
    },
    {
      id: 4,
      licensePlate: 'MNO-2345',
      make: 'Toyota',
      model: 'Hiace',
      year: 2018,
      type: 'Van',
      status: 'active',
      location: 'Mecca, Saudi Arabia',
      driver: 'Noura Al Zahrani',
      lastServiceDate: '2024-06-01',
      warnings: 'Brake Pads Worn',
      progress: 65
    },
    {
      id: 5,
      licensePlate: 'PQR-6789',
      make: 'Chevrolet',
      model: 'Tahoe',
      year: 2022,
      type: 'SUV',
      status: 'active',
      location: 'Tabuk, Saudi Arabia',
      driver: 'Abdullah Al Dossary',
      lastServiceDate: '2024-05-20',
      warnings: 'No Warnings',
      progress: 90
    },
    {
      id: 6,
      licensePlate: 'STU-3456',
      make: 'Hyundai',
      model: 'County',
      year: 2020,
      type: 'Other',
      status: 'maintenance',
      location: 'Abha, Saudi Arabia',
      driver: 'Yousef Al Shammari',
      lastServiceDate: '2024-04-10',
      warnings: 'Engine Check',
      progress: 30
    },
    {
      id: 7,
      licensePlate: 'VWX-7890',
      make: 'MAN',
      model: 'TGS',
      year: 2017,
      type: 'Truck',
      status: 'active',
      location: 'Hail, Saudi Arabia',
      driver: 'Fatimah Al Ghamdi',
      lastServiceDate: '2024-05-05',
      warnings: 'No Warnings',
      progress: 75
    },
    {
      id: 8,
      licensePlate: 'YZA-1235',
      make: 'Nissan',
      model: 'Urvan',
      year: 2021,
      type: 'Van',
      status: 'inactive',
      location: 'Medina, Saudi Arabia',
      driver: 'Saad Al Mutairi',
      lastServiceDate: '2024-02-28',
      warnings: 'Battery Low',
      progress: 0
    }
  ]
}
