export const db = [
  {
    id: 1,
    fullName: 'Fahad Al Saud',
    company: 'Riyadh Logistics Co.',
    role: 'hub_manager',
    username: 'falsaud',
    country: 'Saudi Arabia',
    contact: '+966 11 123 4567',
    email: 'fahad.alsaud@riyadhlogistics.sa',
    currentPlan: 'enterprise',
    status: 'active',
    avatar: '',
    avatarColor: 'primary'
  },
  {
    id: 2,
    fullName: 'Aisha Al Harbi',
    company: 'Jeddah Transport',
    role: 'dispatcher',
    username: 'aalharbi',
    country: 'Saudi Arabia',
    contact: '+966 12 234 5678',
    email: 'aisha.harbi@jeddahtransport.sa',
    currentPlan: 'team',
    status: 'pending',
    avatar: '/images/avatars/3.png'
  },
  {
    id: 3,
    fullName: 'Salman Al Qahtani',
    company: 'Dammam Cargo',
    role: 'driver',
    username: 'salqahtani',
    country: 'Saudi Arabia',
    contact: '+966 13 345 6789',
    email: 'salman.qahtani@dammamcargo.sa',
    currentPlan: 'enterprise',
    status: 'active',
    avatar: '/images/avatars/1.png'
  },
  {
    id: 4,
    fullName: 'Maha Al Otaibi',
    company: 'Mecca Freight',
    role: 'warehouse_staff',
    username: 'malotaibi',
    country: 'Saudi Arabia',
    contact: '+966 12 456 7890',
    email: 'maha.otaibi@meccafreight.sa',
    currentPlan: 'team',
    status: 'inactive',
    avatar: '/images/avatars/3.png'
  },
  {
    id: 5,
    fullName: 'Abdullah Al Dossary',
    company: 'Tabuk Express',
    role: 'driver',
    username: 'aldossary',
    country: 'Saudi Arabia',
    contact: '+966 14 567 8901',
    email: 'abdullah.dossary@tabukexpress.sa',
    currentPlan: 'enterprise',
    status: 'pending',
    avatar: '/images/avatars/1.png'
  },
  {
    id: 6,
    fullName: 'Noura Al Zahrani',
    company: 'Khobar Movers',
    role: 'customer_service',
    username: 'nalzahrani',
    country: 'Saudi Arabia',
    contact: '+966 13 678 9012',
    email: 'noura.zahrani@khobarmovers.sa',
    currentPlan: 'company',
    status: 'active',
    avatar: '',
    avatarColor: 'error'
  },
  {
    id: 7,
    fullName: 'Yousef Al Shammari',
    company: 'Hail Logistics',
    role: 'warehouse_staff',
    username: 'yalshammari',
    country: 'Saudi Arabia',
    contact: '+966 16 789 0123',
    email: 'yousef.shammari@haillogistics.sa',
    currentPlan: 'company',
    status: 'pending',
    avatar: '',
    avatarColor: 'warning'
  },
  {
    id: 8,
    fullName: 'Fatimah Al Ghamdi',
    company: 'Jazan Shipping',
    role: 'dispatcher',
    username: 'fghamdi',
    country: 'Saudi Arabia',
    contact: '+966 17 890 1234',
    email: 'fatimah.ghamdi@jazanshipping.sa',
    currentPlan: 'enterprise',
    status: 'pending',
    avatar: '/images/avatars/4.png'
  },
  {
    id: 9,
    fullName: 'Saad Al Mutairi',
    company: 'Najran Cargo',
    role: 'driver',
    username: 'salmutairi',
    country: 'Saudi Arabia',
    contact: '+966 17 901 2345',
    email: 'saad.mutairi@najrancargo.sa',
    currentPlan: 'team',
    status: 'pending',
    avatar: '/images/avatars/2.png'
  },
  {
    id: 10,
    fullName: 'Reem Al Subaie',
    company: 'Al Jouf Delivery',
    role: 'admin',
    username: 'ralsubaie',
    country: 'Saudi Arabia',
    contact: '+966 14 234 5678',
    email: 'reem.subaie@aljoufdelivery.sa',
    currentPlan: 'company',
    status: 'inactive',
    avatar: '/images/avatars/5.png'
  }
]
